# Generated by Django 5.2.4 on 2025-11-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('breakfast', 'Основа для завтрака'), ('ingredient', 'Добавка'), ('drink', 'Напиток'), ('egg', 'Яйца'), ('cook_method', 'Способ приготовления'), ('utensil', 'Приборы')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('order_items', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Принят'), ('cooking', 'Готовится'), ('ready', 'Готов'), ('completed', 'Выдан')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
