# Generated by Django 5.2.4 on 2025-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Основа для завтрака'), ('ingredient', 'Добавка'), ('drink', 'Напиток'), ('ingredient', 'Инградиенты'), ('cook_method', 'Способ приготовления'), ('utensil', 'Приборы')], max_length=20),
        ),
    ]
