# Generated by Django 5.2.4 on 2025-11-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'шт'), ('gram', 'г'), ('ml', 'мл'), ('slice', 'ломтик'), ('spoon', 'ложка'), ('portion', 'порция')], default='piece', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('base', 'Основа для завтрака'), ('ingredient', 'Ингредиенты'), ('drink', 'Напитки'), ('cook_method', 'Способ приготовления'), ('utensil', 'Приборы')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.client'),
        ),
    ]
